config/routes.rb
Rails.application.routes.draw do
  
  resources 'articles' 
  root 'articles#home'
  get '/home', to:'articles#home'
  get '/show/:id', to: 'articles#show'
  get '/about', to:'articles#about'
  get '/delete/:id', to:'articles#destroy'
  get '/search', to: "articles#search"
  resources 'customers'
  get '/signup', to:'customers#new'
  get '/login', to:'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to:'sessions#destroy'
  resources 'categories'
  resources 'articles' do
  resources 'comments'
  post '/add', to:'comments#create'
  end 
  
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :customer
	has_many :article_categories
	has_many :categories, through: :article_categories
	has_many :comments, dependent: :destroy
	validates :title, presence:true, length:{minimum:4,maxmium:100}
	validates :description , presence:true, length:{minimum:4,maxmium:350}

	def self.matches(field_param,param)
      where("#{field_param} like?","%#{param}%")
    end  
    def self.title_matches(param)
       matches('title',param) 
    end   
    def self.description_matches(param)
       matches('description',param)
    end   
    def self.search(param)
    	param.strip!
        serach_result= (title_matches(param) +description_matches(param)).uniq
        return nil unless serach_result
        serach_result
    end
end	
'''Article.all
article=Article.first
article.categories=> Empty list

category=Category.last
category.articles<<article

article=Article.last
article.categories<<category
'''

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :get_article, only:[:show,:edit,:update,:destroy]
	def index
		@article=Article.paginate(page: params[:page], per_page: 5)
	end
	def home
	end 
	def show
		#@article=Article.find(params[:id])
	end	
	def about
	end	
	def new
		@article=Article.new
	end 
	def edit
		#@article=Article.find(params[:id])
	end	
	def create
		@article=Article.new(get_param)
		#@article.save
		@article.customer=Customer.find(session[:customer_id])
		#render plain: @article.inspect
		if @article.save
			flash[:notice]="Sucessfully Created the article"
			redirect_to article_path(@article)
	    else
	    render 'new'
	    end		
	end 
    def update
    	#@article=Article.find(params[:id])
    	if @article.update(get_param)
    		flash[:notice]="Successfully updated the article"
    		redirect_to article_path(@article)
    	else
    	   render 'edit'
    	end 
    end	
    def destroy
       	#@article=Article.find(params[:id])
       	@article.destroy
       	redirect_to root_path
    end
    private
    def get_article
        @article=Article.find(params[:id])
    end 
    def get_param
        params.require(:article).permit(:title,:description,category_ids:[])
    end  
    def search 
    	if params[:result].present?
    		@result=Article.search(params[:result])
    		put(params[:result])
            if @result 
            	 flash[:notice]=" some valid keyword:"
            	 render 'articles/search'
            else
        	   flash[:alert]="Kindly provide some valid keyword:"
               render 'articles/search'
            end
        else
           flash[:alert]="Kindly provide some keyword name:"
           render 'articles/search'
        end
    end           	
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.html.erb
<h2>Add a comment:</h2>
<%= form_with(model:  [@article, @article.comments.build]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <%= link_to "Destroy Comment", article_comment_path(comment.article,comment) ,method: :delete %>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
<% if @article.errors.any? %>
 <h2>Folowing Error message is occuring </h2>
 <ul>
 	<% @article.errors.full_messages.each do|msg| %>
 	 <li><%= msg %> </li>
 	 <%end%>
 	</ul>
 	<%end%>
<%=form_with model: @article, class:"shadow-lg p-3 mb-5 bg-white rounded" do |form| %>
<div class="mb-3">

	<%= form.label :title,class:"form-label" %><br> 
	<%= form.text_field :title,class:"form-control change" %>

</div>
<p>
	<%= form.label :Description,class:"form-label" %><br> 
	<%= form.text_area :description,class:"form-control change" %>
</p>
<%= form.label :'Article Category',class:"form-label" %><br> 
<%= form.collection_select :category_ids, Category.all, :id, :name, {:prompt => "Please Select a Category"}, {:multiple => true, class:"form-control"} %>

<p>
	<%= form.submit %>
</p>
<%end %>
</div>

app/views/articles/_messages.html.erb
<% flash.each do |name,msg| %>

<div id="message" class="container">
    
        <%= msg %>
    
    </div>


      <!-- <h1><%= msg %><h1> -->
    <% end %>

app/views/articles/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <%=link_to "Alpha-blog", root_path,class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto  mb-lg-0">
        <li class="nav-item ">
          <%=link_to "Articles", articles_path,class:"nav-link active" %>
         
        </li>
        <li class="nav-item">
          <%=link_to "Blogger", customers_path,class:"nav-link active" %>
         
        </li>
        <li class="nav-item ">
           <%=link_to "NewArticle", new_article_path,class:"nav-link active"%>
         
        </li>
        <!-- <li class="nav-item">
           <%=link_to " About", about_path,class:"nav-link active"%>
        </li> --> 
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role='button' data-bs-toggle="dropdown" aria-expanded="false">
          Article Page
            </a>
           <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%if logged_in %>
           <li><%= link_to "New Article",new_article_path,class:"dropdown-item"%></li>
         <li> <%= link_to "Show Article",articles_path,class:"dropdown-item"%></li>
         <%else%>
         <li> <%= link_to "Show Article",articles_path,class:"dropdown-item"%></li>
          <%end%>
          </ul>
        </li>
          <%if logged_in && current_user.admin%>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role='button' data-bs-toggle="dropdown" aria-expanded="false">
          Article Category
            </a>
           <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            
             <li><%= link_to "New Category",new_category_path,class:"dropdown-item"%></li>
             <li> <%= link_to "Show Category",categories_path(@category),class:"dropdown-item"%></li>
           

          
          </ul>
        </li>
         <%end%>
        <%if logged_in %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role='button' data-bs-toggle="dropdown" aria-expanded="false">
          User Profile
            </a>
           <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%if logged_in && current_user.admin%>
         <li><%= link_to current_user.username,customer_path(current_user),class:"dropdown-item"%></li>
         <li> <%= link_to "Edit User",edit_customer_path(current_user),class:"dropdown-item"%></li>
        <!--   <li><%= button_to "Delete User",customer_path(current_user),class:"dropdown-item",method: :delete%></li> -->
          <%else%>
          <li><%= link_to current_user.username,customer_path(current_user),class:"dropdown-item"%></li>
          <%end%>
          
          </ul>
        </li>

        <li class="nav-item">
           <%=link_to " Logout", logout_path,class:"nav-link active",method: :delete %>
         
        </li>
        <%else%>
        <li class="nav-item">
           <%=link_to " Login", login_path,class:"nav-link active"%>    
        </li>
        <li class="nav-item"> 
          <%= link_to "Signup",signup_path,class:"nav-link active"%>
            
          </li>



        <%end%>
      </ul>
      <%= form_tag search_path, method: :get do |form| %>
    <div class="row">
      <div class="col-9">
        <%= text_field_tag :result, params[:result], placeholder:"Enter keyword", class:"form-control me-3" %>
      </div>
      <div class="col-3">
        <%= button_tag type: :submit, class:"btn btn-warning" do  %>
          <%= 'Search'%>
        <%end%>
      </div>
    </div>
  <% end %>
    </div>
  </div>
</nav>

app/views/articles/about.html.erb
<h1>Welcome to About Page</h1>

<h1 class="align-middle m-5" style="font-style:bolder; text-decoration: underline;"><%= @article.title %></h1>
<p  style= "font-size: 20px;"><%= @article.description %></p>

<div>
  <%if logged_in %>
<%= link_to "Edit", edit_article_path(@article) ,class:"btn btn-primary"%></li>
<%if current_user.admin %>
  <%= button_to "Destroy", article_path(@article), class:"btn btn-primary",method: :delete %></li>
</div>
<% end %>
<%end %>

app/views/articles/edit.html.erb
<h1>Welcome to newpage</h1>
<%= render 'form'%>
<p>
	<%= link_to "Back to page",articles_path%> || 
	<%= link_to "show", article_path(@article)%> </p>

app/views/articles/home.html.erb
<div class="container">

	<div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Welcome to Korean Learning</h1>
        
        <p class="col-md-12 fs-4 ">
      
          Nowadays most of the youngest eager to learn Korean.Here you can experience good Korean learning.This page direct you to read all the korean related articles and also you can share your knowledge in korean using create article.
      
        </p>
    
        <%= link_to "Watch Article",articles_path,class:"btn btn-primary btn-lg mr-5"%> 
        <%if logged_in %>
        <%= link_to 'Create New Article', new_article_path , class:"btn btn-warning btn-lg"%>
   <%end%>
      </div>
    </div>

<div class="cat-top-wrap">
<div class="cat-top section" id="Top-Text-Area"><div class="widget HTML" data-version="1" id="HTML656">
<div class="widget-content">
</div>
<div class="clear"></div>
</div></div>
<div class="cat-top section" id="Top-Categories" style="display: block;
width: 100%;"><div class="widget HTML" data-version="1" id="HTML5">
<div class="widget-content">
<a href="#">

<img src="https://1.bp.blogspot.com/-zPAwndxr-E0/Wqttdt7aR-I/AAAAAAAAHwk/U9N1ELB3PcMgotwbEHZOyZ3HvUcSrl_YACLcBGAs/w850-h500-p-k-no-nu/Layer-5471-770x454.jpg">



</a>
</div>
<div class="clear"></div>
</div><div class="widget HTML" data-version="1" id="HTML4">
<div class="widget-content">
<a href="#">

<img src="https://4.bp.blogspot.com/-03UsuiMAsKo/WqttF17tOCI/AAAAAAAAHwU/1L9ejxpyvPUZFFinB64eP3lI5my5FbNhACLcBGAs/w850-h500-p-k-no-nu/Layer-546.jpg">



</a>
</div>
<div class="clear"></div>
</div><div class="widget HTML" data-version="1" id="HTML3">
<div class="widget-content">
<a href="#">

<img src="https://1.bp.blogspot.com/-fBY-keIxvnw/Wqtsu-YEFwI/AAAAAAAAHwI/KxauoshRQM4k0wHo3qOA5O9Z-I4v0kYvwCLcBGAs/w850-h500-p-k-no-nu/Layer-545.jpg">

</a>
</div>
<div class="clear"></div>
</div></div>
</div>

</div>

app/views/articles/index.html.erb
<h1>The Article Lists </h1>

<% @article.each do |article|%>
<div class=container>
<div class="row d-flex justify-content-center">
	<div class="col-8">

<div class="card text-center mb-5">
  <div class="card-header">
   <h2>Created By:<%= article.customer.username %></h2>
   <% if article.categories.any?%>
    <%if logged_in && current_user.admin%>
   <h5><span class="m-3">Category:</span><%=render article.categories%></h5>
   <%end%>
   <%end%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= article.title %></h5>
    <p class="card-text"><%= article.description %></p>
    <%= link_to "show",article_path(article.id),class:"btn btn-info"%>
    <%if logged_in%>
    <%= link_to "Edit",edit_article_path(article.id), class:"btn btn-primary"%>
    <%if logged_in && current_user.admin%>
    <%= button_to "Delete",article_path(article.id), method: :delete ,class:"btn btn-warning" ,data: { confirm: 'Are you sure?' }%>
    <%end%>
    <%= link_to 'New Article', new_article_path , class:"btn btn-info"%>
    <%end %>
  </div>
  <div class="card-footer text-muted">
    <%= article.created_at %>
  </div>
</div>
</div>
</div>
</div>
</div>

<% end%>

	<div class="flickr_pagination d-flex justify-content-center m-5">
    <%= will_paginate @article, :container => false %>
  </div>
	







<table border='1' class="table table-success table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Description</th>
			<th colspan="3">Action</th>
		</tr>
	</thead>
	<% @article.each do |article| %>
	<tr>
	<td> <%= article.id %></td>
	<td><%= article.title %></td>
	<td><%= article.description %></td>
	<td><%= link_to "show",article_path(article.id)%></td>
	<td><%= link_to "Edit",edit_article_path(article.id)%></td>
	<td><%= link_to "Delete",article_path(article), method: :delete %></td>
	</tr>
	<% end%>
	</tbody>	
	<table>		
		<p>
		<%= link_to 'New Article', new_article_path , class:"btn btn-info"%>
	</p>

app/views/articles/new.html.erb
<h1>Welcome to newpage</h1>
<%= render 'form'%>
<div class="nbtn">
<p><%= link_to "Back to page",articles_path,class:"btn btn-primary"%> </p>
</div>

app/views/articles/search.html.erb
<h1>Welcome to About Page</h1>
<%if @result%>
<% @result.each do |result| %>
<h1 class="align-middle m-5" style="font-style:bolder; text-decoration: underline;"><%= result.title %></h1>
<p  style= "font-size: 20px;"><%= result.description %></p>

<%end%>
<%else%>
<p>no dara</p>
<%end%>

app/views/articles/show.html.erb
<h1 class="align-middle m-5" style="font-style:bolder; text-decoration: underline;"><%= @article.title %></h1>
<p  style= "font-size: 20px;"><%= @article.description %></p>

<div>
  <%if logged_in %>
<%= link_to "Edit", edit_article_path(@article) ,class:"btn btn-primary"%></li>
<%if current_user.admin %>
  <%= button_to "Destroy", article_path(@article), class:"btn btn-primary",method: :delete %></li>
</div>
<% end %>
<%end %>


<br>

<h4 class="font-italic mb-3" style="font-family:Goudy Old Style";>Please leave your valuable comment:</h4>
<%= form_with(model:  [@article, @article.comments.build]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter, class:"form-control w-50" %>
  </p>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :body ,class:"form-control w-50" %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  
<% end %>

<br>

 
 
<h4 class="font-italic" style="font-family:Goudy Old Style"> comment lists :</h4>


  <div class="col-md-8 col-lg-6">
    <div class="card shadow-0 border"  >
      <div class="card-body p-4 commentcolor" style="background-color: #f0f2f5;" >
        
<% @article.comments.each do |comment| %>

        <div class="card mb-4">
          <div class="card-body" style="background-color: #fff; border-radius: 0.5rem;">
            <p><%= comment.body %></p>

            <div class="d-flex justify-content-between">
              <div class="d-flex flex-row align-items-center">
                
                <p class="small mb-0 ms-2">-<%= comment.commenter %></p>
              </div>
            
            </div>
          </div>
        </div>

       
       <% end %>

        
      </div>
    </div>
  </div>


<!--<div class="card my-1"> # place this card blow the post body.
  <div class="card-body">
    <p class="font-weight-bold">Comments</p>
    <%= form_with(model: [@article, @article.comments.build]) do |f| %>
    <div class="form-group">
        <%= f.label 'New commeter' %>
        <%= f.text_area :commenter, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label 'New comment' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>!-->