config/routes.rb
Rails.application.routes.draw do
  
  resources 'articles' 
  root 'articles#home'
  get '/home', to:'articles#home'
  get '/show/:id', to: 'articles#show'
  get '/about', to:'articles#about'
  get '/delete/:id', to:'articles#destroy'
  get '/search', to: "articles#search"
  resources 'customers'
  get '/signup', to:'customers#new'
  get '/login', to:'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to:'sessions#destroy'
  resources 'categories'
  resources 'articles' do
  resources 'comments'
  post '/add', to:'comments#create'
  end 
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence:true,uniqueness:{case_sensitive:false}
end	

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :get_article, only:[:show,:update]
	def index
		#@category=Category.paginate(page: params[:page], per_page: 5)
	end                                                                             
	def show
		#@category=Article.find(params[:id])
	end	
	
	def new
		@category=Category.new
	end 
	def index
		@category=Category.all
	end	
	def edit
		@category=Category.find(params[:id])
    end 
    def update
    	@category=Category.find(params[:id])
    	if @category.update(get_param)
    		flash[:notice]="Successfully updated the article"
    		redirect_to articles_path
    	else
    	   render 'edit'
    	end 
    end		

	def create
		@category=Category.new(get_param)
		#@article.save
		if @category.save
			flash[:notice]="Sucessfully Created the article"
			redirect_to new_category_path(@article)
	    else
	    render 'new'
	    end		
	end 
   
    private
    def get_article
        @category=Category.find(params[:id])
    end 
    def get_param
        params.require(:category).permit(:name)
    end        	
end

app/views/categories/_category.html.erb
<%= link_to category.name,category_path(category),class:"btn btn-primary"%>

app/views/categories/_catname.html.erb
<%= category.name %>

app/views/categories/edit.html.erb
<div class="container">

<%=form_with model: @category, class:"shadow-lg p-3 mb-5 bg-white rounded" do |form| %>
<div class="mb-3">

	<%= form.label :Category_name,class:"form-label" %><br> 
	<%= form.text_field :name,class:"form-control change" %>

</div>
<p>
	<%= form.submit %>
</p>
<%end %>
</div>

app/views/categories/index.html.erb
<h1>index page</h1>

<% @category.each do |category|%>
<div class=container>
<div class="row d-flex justify-content-center">
	<div class="col-8">

<div class="card text-center mb-5">
  <div class="card-header">
   
   <%= link_to category.name,category%>
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text"><%= pluralize(category.articles.count,"Article")%></p>
  </div>
  <div class="card-footer text-muted">
    <%= category.created_at %>
  </div>
</div>
</div>
</div>
</div>
</div>

<% end%>

app/views/categories/new.html.erb
<div class="container">
<h1>create category</h1>
<%=form_with model: @category, class:"shadow-lg p-3 mb-5 bg-white rounded" do |form| %>
<div class="mb-3">

	<%= form.label :Category_name,class:"form-label" %><br> 
	<%= form.text_field :name,class:"form-control change" %>

</div>

<p>
	<%= form.submit%>
</p>
<%end %>
</div>

app/views/categories/show.html.erb
<h1>show page</h1>
<p>Category Name:<%= @category.name %></p>


<div class=container>

<div class="card text-center center-block m-4 user" >
   

</div>
</div>

<div class=container>
<div class="row d-flex justify-content-center">
  <div class="col-md-8">
<div class="card text-center  mb-5">
<div class="card-header">
  <h2> <%= @category.name %></h2>
</div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to "Edit Article Category" , edit_category_path(@category),class:"btn btn-outline-warning"%></h5>
    <p class="card-text"></p>
    
  </div>
  <div class="card-footer text-muted">
    <%= @category.created_at %>
  </div>
</div>
</div>
</div>
</div>
</div>